# -*- coding: utf-8 -*-
"""housing_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQ6Ip4WwN-n1AZS0FHg4SdXR4qHCyJlj

# Housing Linear Regression by Syabab

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

"""## Importing the dataset"""

dataset = pd.read_csv('housing.csv')
#drop non numeric column
dataset = dataset.select_dtypes(include=[np.number]).dropna()
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, :-1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=42)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

"""## Visualising the Training set results"""

plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, model.predict(X_train), color = 'blue')
plt.xlabel("Median Income")
plt.ylabel("Median House Value")
plt.title("Linear Regression: Median Income vs House Value")
plt.show()

"""## Visualising the Test set results"""

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, model.predict(X_train), color = 'blue')
plt.xlabel("Median Income")
plt.ylabel("Median House Value")
plt.title("Linear Regression: Median Income vs House Value")
plt.show()